name: CI

on: [push]

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Github Action for SwiftLint
      uses: norio-nomura/action-swiftlint@3.0.1

  Build:
    runs-on: macos-11
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Select latest Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Build app
      run: xcodebuild -project 'MRZParser.xcodeproj' -scheme 'MRZParser' -destination 'generic/platform=iOS' -configuration Release build CODE_SIGNING_ALLOWED=NO | xcpretty

  Test:
    runs-on: macos-11
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Select latest Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Run tests
      if: steps.cache.outputs.cache-hit != 'true'
      run: xcodebuild -project 'MRZParser.xcodeproj' -scheme 'MRZParser' -destination 'platform=iOS Simulator,name=iPhone 13 Pro' clean build-for-testing test | xcpretty
